'use client';

import { ArrowLeft, ArrowRight, Check, Clock3, ExternalLink, FileCode2, MessageCircle, Palette, ShieldCheck } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';

const WHATSAPP = '6287886626130';
const catalog: Record<string, {name:string;category:string;price:string;demo:string;image:string;summary:string;timeline:string;pages:string[];features:string[]}> = {
  'nusa-coffee': {name:'Nusa Coffee',category:'Kuliner',price:'Rp2.500.000',demo:'/demos/nusa-coffee/index.html',image:'/demos/nusa-coffee/cafe-interior.webp',summary:'Landing page hangat untuk kafe, coffee shop, dan produk minuman lokal.',timeline:'7–10 hari kerja',pages:['Beranda satu halaman','Menu unggulan','Cerita bisnis','Lokasi & kontak'],features:['Desain responsif','Integrasi WhatsApp','Google Maps','SEO dasar','2 kali revisi']},
  'arka-property': {name:'Arka Residence',category:'Properti',price:'Rp3.500.000',demo:'/demos/arka-residence/index.html',image:'/demos/arka-residence/residence-hero.webp',summary:'Presentasi premium untuk perumahan, apartemen, dan agen properti.',timeline:'10–14 hari kerja',pages:['Beranda proyek','Tipe unit','Fasilitas','Lokasi & form prospek'],features:['Galeri properti','Daftar unit','WhatsApp & form','SEO dasar','2 kali revisi']},
  'selaras-studio': {name:'Selaras Studio',category:'Jasa Profesional',price:'Rp2.750.000',demo:'/demos/selaras-studio/index.html',image:'/demos/selaras-studio/studio-photo.webp',summary:'Website editorial untuk konsultan, agensi, dan jasa profesional.',timeline:'7–12 hari kerja',pages:['Beranda','Portofolio','Layanan','Profil & kontak'],features:['Portofolio visual','Animasi ringan','WhatsApp','SEO dasar','2 kali revisi']},
  'loka-store': {name:'Loka Store',category:'Toko Online',price:'Rp4.500.000',demo:'/demos/loka-store/index.html',image:'/demos/loka-store/homeware-hero.webp',summary:'Etalase produk modern dengan alur pemesanan yang ringkas.',timeline:'14–21 hari kerja',pages:['Beranda toko','Katalog','Detail produk','Tentang & bantuan'],features:['Katalog produk','Filter kategori','Pesan via WhatsApp','SEO dasar','3 kali revisi']},
  'nexora-logistics': {name:'Nexora Logistics',category:'Aplikasi Web',price:'Rp12.500.000',demo:'/demos/nexora-logistics/index.html',image:'/images/logistics-dashboard.webp',summary:'Dashboard operasional interaktif untuk armada, pengiriman, dan laporan.',timeline:'4–8 minggu',pages:['Dashboard utama','Pengiriman','Armada','Laporan operasional'],features:['Login pengguna','Filter data','Status real-time','Ekspor laporan','Pengujian & panduan']},
  'hospital-sentosa': {name:'Sentosa Medical Center',category:'Kesehatan',price:'Rp4.500.000',demo:'/demos/hospital-sentosa/index.html',image:'/demos/hospital-sentosa/hero.webp',summary:'Website rumah sakit modern dengan layanan, dokter, fasilitas, dan pendaftaran janji.',timeline:'14–21 hari kerja',pages:['Beranda','Layanan medis','Jadwal dokter','Fasilitas & kontak'],features:['Form janji dokter','Daftar spesialis','Informasi IGD','SEO dasar','3 kali revisi']},
  'desa-sukamaju': {name:'Desa Sukamaju',category:'Pemerintahan',price:'Rp4.000.000',demo:'/demos/desa-sukamaju/index.html',image:'/demos/desa-sukamaju/hero.webp',summary:'Portal pelayanan desa untuk administrasi warga, berita, agenda, dan transparansi.',timeline:'14–21 hari kerja',pages:['Beranda desa','Pelayanan warga','Potensi & berita','Transparansi & kontak'],features:['Form pengajuan','Agenda desa','Aspirasi warga','SEO dasar','3 kali revisi']},
  'nawasena-campus': {name:'Nawasena University',category:'Pendidikan',price:'Rp4.500.000',demo:'/demos/nawasena-campus/index.html',image:'/demos/nawasena-campus/hero.webp',summary:'Website sekolah atau kampus untuk program, admisi, agenda, dan kehidupan akademik.',timeline:'14–21 hari kerja',pages:['Beranda','Program studi','Kehidupan kampus','Admisi & kontak'],features:['Katalog program','Form admisi','Agenda akademik','SEO dasar','3 kali revisi']},
  'harapan-bersama': {name:'Harapan Bersama',category:'Yayasan',price:'Rp3.750.000',demo:'/demos/harapan-bersama/index.html',image:'/demos/harapan-bersama/hero.webp',summary:'Website yayasan sosial yang menampilkan program, dampak, laporan, dan jalur donasi.',timeline:'10–18 hari kerja',pages:['Beranda','Program sosial','Dampak & cerita','Donasi & kontak'],features:['Form donasi','Laporan dampak','Cerita penerima manfaat','SEO dasar','3 kali revisi']},
  'koperasi-tumbuh': {name:'Koperasi Tumbuh',category:'Koperasi',price:'Rp4.500.000',demo:'/demos/koperasi-tumbuh/index.html',image:'/demos/koperasi-tumbuh/hero.webp',summary:'Website koperasi modern untuk layanan anggota, produk usaha, dan transparansi.',timeline:'14–21 hari kerja',pages:['Beranda','Layanan anggota','Produk usaha','Transparansi & kontak'],features:['Form keanggotaan','Katalog produk','Informasi SHU','SEO dasar','3 kali revisi']},
};
const additions = [['Domain & hosting 1 tahun','Rp750.000'],['Penulisan konten','Rp1.000.000'],['Foto produk / lokasi','Sesuai kebutuhan'],['Halaman tambahan','Rp350.000 / halaman']];

export default function TemplateDetail(){
  const params=useParams<{slug:string}>(); const item=catalog[params.slug]||catalog['nusa-coffee'];
  const [selected,setSelected]=useState<string[]>([]);
  const estimate=useMemo(()=>selected.includes('Domain & hosting 1 tahun')?`${item.price} + Rp750.000`:item.price,[item.price,selected]);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const message=[`Halo MOVETRA, saya ingin memesan template ${item.name}.`,`Nama bisnis: ${data.get('business')}`,`Bidang: ${data.get('industry')}`,`Arah brand: ${data.get('brand')||'-'}`,`Tambahan: ${selected.join(', ')||'Tidak ada'}`,`Estimasi awal: ${estimate}`].join('\n');window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');}
  return <main className="templateDetailPage">
    <header className="detailNav"><div className="container"><a href="/templates"><ArrowLeft/> Kembali ke katalog</a><span>MOVETRA / TEMPLATE DETAIL</span><a href={item.demo} target="_blank">Live demo <ExternalLink/></a></div></header>
    <section className="detailHero"><div className="container detailHeroGrid"><div><span className="detailCategory">{item.category} · SIAP DIKUSTOMISASI</span><h1>{item.name}</h1><p>{item.summary}</p><div className="detailPrice"><small>INVESTASI MULAI</small><b>{item.price}</b><span>Harga final mengikuti kebutuhan konten dan fitur.</span></div><a href="#configure">Konfigurasikan website <ArrowRight/></a></div><div className="detailHeroImage" style={{backgroundImage:`url("${item.image}")`}}><span>LIVE PREVIEW</span><a href={item.demo} target="_blank">Buka demo <ExternalLink/></a></div></div></section>
    <section className="detailTrust"><div className="container"><span><Clock3/><b>{item.timeline}</b><small>Estimasi pengerjaan</small></span><span><Palette/><b>Sesuai brand</b><small>Warna, logo, dan konten</small></span><span><FileCode2/><b>Kode mandiri</b><small>Mudah dikembangkan</small></span><span><ShieldCheck/><b>Dukungan</b><small>Setelah peluncuran</small></span></div></section>
    <section className="detailScope"><div className="container detailScopeGrid"><div><span>YANG ANDA DAPATKAN</span><h2>Ruang lingkup yang jelas sejak awal.</h2><p>Template menjadi proyek khusus milik bisnis Anda. Kami menyesuaikan hierarki konten dan identitas visual, bukan hanya mengganti nama.</p></div><div className="scopeCards"><article><b>HALAMAN / MODUL</b>{item.pages.map(x=><span key={x}><Check/>{x}</span>)}</article><article><b>FITUR TERMASUK</b>{item.features.map(x=><span key={x}><Check/>{x}</span>)}</article></div></div></section>
    <section id="configure" className="configSection"><div className="container configGrid"><div><span>KONFIGURATOR PROYEK</span><h2>Susun kebutuhan Anda.</h2><p>Pilih layanan tambahan, isi informasi singkat, lalu kirim rangkumannya ke WhatsApp. Estimasi ini belum merupakan penawaran final.</p><div className="additionList">{additions.map(([name,price])=><label key={name}><input type="checkbox" checked={selected.includes(name)} onChange={()=>setSelected(s=>s.includes(name)?s.filter(x=>x!==name):[...s,name])}/><span><b>{name}</b><small>{price}</small></span></label>)}</div></div><form onSubmit={submit}><h3>Ringkasan pemesanan</h3><label>Nama bisnis*<input name="business" required placeholder="Contoh: Kopi Senja"/></label><label>Bidang usaha*<input name="industry" required placeholder="Kuliner, properti, jasa..."/></label><label>Arah brand<textarea name="brand" rows={3} placeholder="Warna, gaya, atau referensi yang disukai"/></label><div className="estimateBox"><small>ESTIMASI AWAL</small><b>{estimate}</b><span>{selected.length} layanan tambahan dipilih</span></div><button>Kirim ke WhatsApp <MessageCircle/></button></form></div></section>
    <section className="conceptNote"><div className="container"><b>Transparansi MOVETRA</b><p>Demo pada katalog merupakan concept project untuk menunjukkan kualitas desain dan kemampuan teknis. Hasil proyek klien hanya dipublikasikan setelah memperoleh izin.</p></div></section>
  </main>;
}
